import {
  collection,
  addDoc,
  doc,
  updateDoc,
  deleteDoc,
} from "firebase/firestore";
import { db } from "./config";

/**
 * Function that save a new transaction in the database
 * @param {object} data
 * @returns
 * if the process is successful, return the new task id generated by the db
 * if the process failed, return null
 */
export async function save(data) {
  try {
    const docRef = await addDoc(collection(db, "transactions"), data);
    return docRef.id;
  } catch (error) {
    console.log("Error adding document: ", error);
    return null;
  }
}

/**
 * Function that update any change in the transactions
 * @param {string} id
 * @param {object} data
 * @returns
 * if the process is successful, return true; if not, false
 */
export async function updateTransation(id, data) {
  try {
    const docRef = doc(db, "transactions", id);
    await updateDoc(docRef, data);
    return true;
  } catch {
    return false;
  }
}

/**
 * Function that update any change in the settings transactions
 * @param {string} id
 * @param {object} data
 * @returns
 * if the process is successful, return true; if not, false
 */
export async function updateTransationSettings(id, data) {
  try {
    const docRef = doc(db, "settings", id);
    await updateDoc(docRef, data);
    return true;
  } catch {
    return false;
  }
}

/**
 * Function that remove a transaction based on its id
 * @param {string} id
 * @returns
 * if the removing is successful, return true; if not, false
 */
export async function remove(id) {
  try {
    await deleteDoc(doc(db, "transactions", id));
    return true;
  } catch {
    return false;
  }
}
